package com.example.sqldelighttest

import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import androidx.sqlite.db.SupportSQLiteOpenHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import com.example.MyDatabase
import com.example.Team
import com.squareup.sqldelight.android.AndroidSqliteDriver
import com.squareup.sqldelight.runtime.rx.asObservable
import com.squareup.sqldelight.runtime.rx.mapToList

class MainActivity : AppCompatActivity() {
    lateinit var database: MyDatabase

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val config = SupportSQLiteOpenHelper.Configuration.builder(applicationContext)
                .callback(AndroidSqliteDriver.Callback(MyDatabase.Schema))
                .name("test.db")
                .build()
        val helper = FrameworkSQLiteOpenHelperFactory().create(config)
        helper.setWriteAheadLoggingEnabled(true)
        val driver = AndroidSqliteDriver(helper)
        database = MyDatabase(driver)

        database.hockeyPlayerQueries.query1().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query2().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query3().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query4().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query5().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query6().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query7().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query8().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query9().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query10().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query11().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query12().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query13().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query14().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query15().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query16().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query17().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query18().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query19().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query20().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query21().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query22().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query23().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query24().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query25().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query26().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query27().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query28().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query29().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query30().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query31().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query32().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query33().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query34().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query35().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query36().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query37().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query38().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query39().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query40().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query41().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query42().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query43().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query44().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query45().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query46().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query47().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query48().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query49().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query50().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query51().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query52().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query53().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query54().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query55().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query56().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query57().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query58().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query59().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query60().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query61().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query62().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query63().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query64().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query65().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query66().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query67().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query68().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query69().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query70().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query71().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query72().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query73().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query74().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query75().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query76().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query77().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query78().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query79().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query80().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query81().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query82().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query83().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query84().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query85().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query86().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query87().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query88().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query89().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query90().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query91().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query92().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query93().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query94().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query95().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query96().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query97().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query98().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query99().asObservable().mapToList().subscribe()
        database.hockeyPlayerQueries.query100().asObservable().mapToList().subscribe()

        insertItem()

        setContentView(R.layout.activity_main)
    }

    fun insertItem() {
        database.hockeyPlayerQueries.insertTeam("name1", "coach1", false)
    }
}
